<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HC13-08" name="Flipkart_2.0_IE" tests="8" failures="1" timestamp="29 May 2016 06:26:59 GMT" time="0.02" errors="0">
  <testcase name="createUser" time="0.01" classname="com.croma.example.TestNGAnnotation"/>
  <testcase name="createUser" time="0.01" classname="com.croma.example.Demo"/>
  <testcase name="login" time="0.0" classname="com.croma.example.TestNGAnnotation"/>
  <testcase name="login" time="0.0" classname="com.croma.example.Demo"/>
  <testcase name="cselectCategroy" time="0.0" classname="com.croma.example.TestNGAnnotation"/>
  <testcase name="selectCategroy" time="0.0" classname="com.croma.example.Demo">
    <failure type="java.lang.Exception" message="my exception">
      <![CDATA[java.lang.Exception: my exception
	at com.croma.example.Demo.selectCategroy(Demo.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- selectCategroy -->
  <testcase name="buyItem" time="0.0" classname="com.croma.example.Demo">
    <skipped/>
  </testcase> <!-- buyItem -->
  <testcase name="shippingDetails" time="0.0" classname="com.croma.example.Demo">
    <skipped/>
  </testcase> <!-- shippingDetails -->
</testsuite> <!-- Flipkart_2.0_IE -->
